# Generated by Django 2.2.2 on 2019-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20190608_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonforecast',
            name='season',
            field=models.CharField(choices=[('WI', 'winter'), ('SP', 'spring'), ('SU', 'summer'), ('AU', 'autumn')], default='W', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accurateforecast',
            name='wind_direction',
            field=models.CharField(choices=[('N', 'north'), ('E', 'east'), ('S', 'south'), ('W', 'west'), ('NE', 'north-east'), ('SE', 'south-east'), ('NW', 'north-west'), ('SW', 'south-west')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seasonforecast',
            name='precipitation',
            field=models.CharField(choices=[('D', 'dry'), ('A', 'average'), ('W', 'wet')], max_length=1),
        ),
    ]
